services:
  # Production version
  gotpop-work:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        - STORYBLOK_ACCESS_TOKEN=${STORYBLOK_ACCESS_TOKEN}
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ../.env
    restart: unless-stopped
    container_name: gotpop-work

  # Development version
  gotpop-work-dev:
    build:
      context: ..
      dockerfile: config/Dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - ../.env
    volumes:
      - ../src:/app/src
      - ../public:/app/public
    restart: unless-stopped
    container_name: gotpop-work-dev
    profiles:
      - dev
